#!/bin/sh

# Restore the backup of the SmartCam config
if [ -e "/home/exp1000/config.ini.backup" ]; then
  cp /home/exp1000/config.ini.backup /home/exp1000/config.ini
  rm -f /home/exp1000/config.ini.backup
fi
